### ISSUE TITLE
Remove Floof

### ISSUE THREAD

**Issue by WaviestBalloon** [Gideon-Foxo/furry-bots#3]
Floof Bot has now been [discontinued]().
A new bot is taking it's place sooner or later.

**Comment by Gideon-Foxo** [comment]
👍 Floof was removed [in the latest update](https://github.com/Gideon-foxo/furry-bots/commit/d25e40abe99729375425e3d006d5b73888a3d095). If you do end up making a new bot I will probably add it to my watch list once I see it on a public listing site. Thank you for taking the time to make an issue, I appreciate it.
