### ISSUE TITLE
Note: Thaldrin

### ISSUE THREAD

**Issue by fangmarks** [Gideon-Foxo/furry-bots#6]
Thaldrin is in kindof a Limbo state right now, since most of his features require access to the Message Content and I haven't gotten around to actually rewriting him. Sometime tho! Soon:tm:

**Comment by Gideon-Foxo** [comment]
I have been aware the project has been on hold pending a fun:tm: rewrite and I thought I removed it? Guess I never ended up doing that woops. Thanks for the heads up ill adjust that when I update it today or tmr.

**Comment by fangmarks** [comment]
You did! Just wanted to let you know that he's not really discontinued, just offline for _extended :>_ maintenance

**Comment by Gideon-Foxo** [comment]
Going to close this now. If you ever bring it back up feel free to let us know. 

We do check the bots on the server and try not to keep updating bots that are down for long periods of time but this isnt tracked in any way. this is something I plan to track it sometime in the future. So letting us know here or in our server is probably the best option to make sure its not missed.

**Comment by fangmarks** [comment]
Will do! I currently don't have much time to work on Thal, so it's gonna be a good while before he'll be back ^^
